name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------
      # 1. Configure AWS Credentials
      # -----------------------------
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change if needed

      # -----------------------------
      # 2. Login to Amazon ECR
      # -----------------------------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -----------------------------
      # 3. Build & Push Docker Image
      # -----------------------------
      - name: Build & Push Image
        run: |
          ECR="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/eks-k6-hpa-demo"
          docker build -t $ECR:latest .
          docker push $ECR:latest

      # -----------------------------
      # 4. Configure kubectl for EKS
      # -----------------------------
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      # -----------------------------
      # 5. Deploy to EKS
      # -----------------------------
      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s/

      # -----------------------------
      # 6. Run K6 load test (optional)
      # -----------------------------
      - name: Run K6 Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/test.js
